config/routes.rb
Landingpage::Application.routes.draw do
  resources :subscribers

  devise_for :users

  root 'static#index'
  get '/about', to: 'static#about', as: "about"
end

app/models/subscriber.rb
class Subscriber < ActiveRecord::Base
  #
  # Validations
  #
  validates_presence_of :email
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  
  before_filter :authenticate_user!
  before_filter :set_meta_data
  
  def set_meta_data(title="App Title", keywords="app, key, words", description="App description.")
    @meta_title, @meta_keywords, @meta_description = title, keywords, description
  end
end

app/controllers/static_controller.rb
class StaticController < ApplicationController
  skip_before_filter :authenticate_user!, only: [:index]
  def index
    @subscriber = Subscriber.new
  end

  def about

  end

end

app/controllers/subscribers_controller.rb
class SubscribersController < ApplicationController
  before_action :set_subscriber, only: [:show, :edit, :update, :destroy]
  skip_before_filter :authenticate_user!, only: [:new, :index, :create]

  # GET /subscribers
  # GET /subscribers.json
  def index
    @subscribers = Subscriber.all
  end

  # GET /subscribers/1
  # GET /subscribers/1.json
  def show
  end

  # GET /subscribers/new
  def new
    @subscriber = Subscriber.new
  end

  # GET /subscribers/1/edit
  def edit
  end

  # POST /subscribers
  # POST /subscribers.json
  def create
    @subscriber = Subscriber.new(subscriber_params)

    respond_to do |format|
      if @subscriber.save
        format.html { redirect_to root_url, notice: 'Subscriber was successfully created.' }
        format.json { render action: 'show', status: :created, location: @subscriber }
      else
        format.html { render action: 'new' }
        format.json { render json: @subscriber.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /subscribers/1
  # PATCH/PUT /subscribers/1.json
  def update
    respond_to do |format|
      if @subscriber.update(subscriber_params)
        format.html { redirect_to @subscriber, notice: 'Subscriber was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @subscriber.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /subscribers/1
  # DELETE /subscribers/1.json
  def destroy
    @subscriber.destroy
    respond_to do |format|
      format.html { redirect_to subscribers_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_subscriber
      @subscriber = Subscriber.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def subscriber_params
      params.require(:subscriber).permit(:email)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/static_helper.rb
module StaticHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= @meta_title %></title>
	<meta name="keywords" content="<%= @meta_keywords %>" />
	<meta name="description" content="<%= @meta_description %>" />
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body class="application <%= controller.controller_name %> <%= controller.controller_name %>-<%= controller.action_name %>">
  <%= render "shared/notice" %>
  <%= render "shared/navbar" %>
  <div class="yield">
    <%= yield %>
  </div>
  <%= render "shared/footer" %>
</body>
</html>

app/views/shared/_footer.html.haml
.container
  .row
    .col-md-3

    .col-md-6
      %span.text-muted Built by
      = link_to "Enghance", "http://www.enghance.com"

    .col-md-3

app/views/shared/_navbar.html.haml
.container
  .row
    .col-md-12.text-right
      %span.text-muted Already invited?
      = link_to "Login", new_user_session_path

app/views/shared/_notice.html.haml
- if flash[:error] and !flash[:error].blank?
  .alert.alert-error.fade.in
    %a.close{"data-dismiss" => "alert", href: "#"} ×
    .container
      %p.error= flash[:error]
- if flash[:notice] and !flash[:notice].blank?
  .alert.alert-info.fade.in
    %a.close{"data-dismiss" => "alert", href: "#"} ×
    .container
      %p.notice= flash[:notice]
- if flash[:alert] and !flash[:alert].blank?
  .alert.alert-warning.fade.in
    %a.close{"data-dismiss" => "alert", href: "#"} ×
    .container
      %p.notice= flash[:alert]

app/views/subscribers/_form.html.haml
= form_for @subscriber do |f|
  - if @subscriber.errors.any?
    #error_explanation
      %h2= "#{pluralize(@subscriber.errors.count, "error")} prohibited this subscriber from being saved:"
      %ul
        - @subscriber.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :email
    = f.text_field :email
  .actions
    = f.submit 'Save'

app/views/subscribers/index.html.haml
%h1 Listing subscribers

%table
  %tr
    %th Email
    %th
    %th
    %th

  - @subscribers.each do |subscriber|
    %tr
      %td= subscriber.email
      %td= link_to 'Show', subscriber
      %td= link_to 'Edit', edit_subscriber_path(subscriber)
      %td= link_to 'Destroy', subscriber, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Subscriber', new_subscriber_path

app/views/subscribers/new.html.haml
%h1 New subscriber

= render 'form'

= link_to 'Back', subscribers_path

app/views/subscribers/show.html.haml
%p#notice= notice

%p
  %b Email:
  = @subscriber.email

= link_to 'Edit', edit_subscriber_path(@subscriber)
\|
= link_to 'Back', subscribers_path